version: "3"
services:
  netlicensing-gateway:
    image: "labs64/netlicensing-gateway"
    ports:
      - "8080:8080"
  ngrok:
    image: "wernight/ngrok"
    ports:
      - "4040:4040"
    command:
      - /bin/sh
      - -c
      - |
        ngrok http netlicensing-gateway:8080
    depends_on:
      - netlicensing-gateway
